# Generated by Django 4.2.4 on 2023-09-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stock_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='export_to_CSV',
            field=models.BooleanField(default=True),
        ),
    ]
